#!/usr/bin/env bash
# This script installs nginx web server

apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
