#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.

apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i '37i\rewrite ^/redirect_me http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
