#!/usr/bin/env bash
# This script fixes the bug that is keeping your Ubuntu container's
# nginx installation from listening on port 80.

apt-get -y update
apt-get -y install nginx
service nginx start
