#!/usr/bin/bash
# This script fixes a bug in your nginx server, allowing it to connect to port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx start
rm /run/nginx.pid
