#!/usr/bin/env bash
# This script displays "Best School" as it loops from 1 - 10. However,
# it displays bad luck for the 4th loop iteration, and
# it displays good luck for the 8th loop iteration,

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
