#!/usr/bin/env bash
# This script configures a given container to run nginx as nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
